### Listar produtos
GET https://localhost:7058/api/agendamento/listar

### Buscar produto por nome
GET https://localhost:7058/api/agendamento/buscar/

### Cadastrar produto
POST https://localhost:7058/api/agendamento/cadastrar
Content-Type: application/json

{
    "AgendamentoId" : "",
    "Usuario" : "Feijão",
    "AgendadiEm":"",
    
}

### Remover produto pelo ID
DELETE https://localhost:7058/api/agendamento/deletar/

### Alterar produto pelo ID
PUT https://localhost:7058/api/agendamento/alterar/
Content-Type: application/json

{
    
}