### Listar os agendamentos 
GET https://localhost:5001/api/agendameto/Listar


### Buscar os agendamentos
GET https://localhost:5001/api/agendamento/buscar/123


### Cadastrar novos agendamentos
POST https://localhost:5001/api/agendameto/cadastrar
Content-Type: application/json

{
  "Cliente": "aaaa",
  "cpf" : "123",
  "Usuario": "Joses",
  "DataAgendamento": ""
}

### Deletar um agendamento
DELETE  https://localhost:5001/api/agendameto/deletar/6


### Alterar um agendamento
PATCH  https://localhost:5001/api/agendamento/alterar
Content-Type: application/json
