### Listar os agendamentos 
GET https://localhost:5111/Agenday/Agendameto/Listar


### Buscar os agendamentos
GET https://localhost:5111/Agenday/Agendamento/buscar


### Cadastrar novos agendamentos
POST https://localhost:5111/Agenday/Agendameto/cadastrar
Content-Type: application/json

{
  "AgendamentoId" : "",
  "nome" : "Tino",
  "AgendadoEm": ""
}

### Deletar um agendamento
DELETE  https://localhost:5111/Agenday/Agendameto/deletar


### Alterar um agendamento
PATCH  https://localhost:5111/Agenday/Agendamento/alterar
Content-Type: application/json