### Listar produtos
GET https://localhost:7058/api/servico/listarservico

### Buscar produto por nome
GET https://localhost:7058/api/servico/buscar/

### Cadastrar produto
POST https://localhost:7058/api/servico/cadastrarservico
Content-Type: application/json

{
    "AgendamentoId" : "",
    "Usuario" : "Feijão",
    "AgendadiEm":"",
    
}

### Remover produto pelo ID
DELETE https://localhost:7058/api/servico/deletar/

### Alterar produto pelo ID
PUT https://localhost:7058/api/servico/alterar/
Content-Type: application/json

{
    
}